/**
 * Bake assets/icons/*.svg into custGeom path fragments for the PageSpec icon
 * vocabulary. Heroicons solid (24×24, fill-based) → <a:pathLst> strings in the
 * registry consumed by src/main/page-spec.ts.
 *
 * Usage: npm run bake:icons -w @genoffice/slides
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import SvgPath from 'svgpath'

const appDir = join(fileURLToPath(new URL('.', import.meta.url)), '..')
const iconsDir = join(appDir, 'assets', 'icons')
const outFile = join(appDir, 'src', 'main', 'icon-registry.generated.ts')

/** Heroicons viewBox is 24×24; OOXML path space uses 216000 (24 × 9000). */
const SCALE = 9000

const px = (v) => Math.round(v * SCALE)

function attrsOf(tag) {
  const attrs = {}
  for (const m of tag.matchAll(/([\w:-]+)\s*=\s*"([^"]*)"/g)) attrs[m[1]] = m[2]
  return attrs
}

function pathXml(d, fillRule) {
  const sp = new SvgPath(d).abs().unshort().unarc()
  let xml = ''
  let opened = false
  sp.iterate((seg) => {
    const [cmd, ...args] = seg
    if (cmd === 'M') {
      xml += `<a:moveTo><a:pt x="${px(args[0])}" y="${px(args[1])}"/></a:moveTo>`
      opened = true
    } else if (cmd === 'L') {
      xml += `<a:lnTo><a:pt x="${px(args[0])}" y="${px(args[1])}"/></a:lnTo>`
    } else if (cmd === 'C') {
      xml +=
        `<a:cubicBezTo>` +
        `<a:pt x="${px(args[0])}" y="${px(args[1])}"/>` +
        `<a:pt x="${px(args[2])}" y="${px(args[3])}"/>` +
        `<a:pt x="${px(args[4])}" y="${px(args[5])}"/></a:cubicBezTo>`
    } else if (cmd === 'Q') {
      xml +=
        `<a:quadBezTo>` +
        `<a:pt x="${px(args[0])}" y="${px(args[1])}"/>` +
        `<a:pt x="${px(args[2])}" y="${px(args[3])}"/></a:quadBezTo>`
    } else if (cmd === 'Z') {
      xml += '<a:close/>'
    }
  })
  if (!opened) return null
  return `<a:path w="216000" h="216000" fill="${fillRule === 'evenodd' ? 'evenOdd' : 'norm'}">${xml}</a:path>`
}

const registry = {}
for (const file of readdirSync(iconsDir).sort()) {
  if (!file.endsWith('.svg')) continue
  const name = basename(file, '.svg')
  const svg = readFileSync(join(iconsDir, file), 'utf8')
  let paths = ''
  for (const m of svg.matchAll(/<path\b([^>]*?)\/>/g)) {
    const attrs = attrsOf(m[1])
    if (!attrs.d) continue
    const xml = pathXml(attrs.d, attrs['fill-rule'])
    if (xml) paths += xml
  }
  if (!paths) {
    console.warn(`skip ${name}: no bakeable <path d> found`)
    continue
  }
  registry[name] = `<a:pathLst>${paths}</a:pathLst>`
}

const body = `/** GENERATED by scripts/bake-icons.mjs from assets/icons (Heroicons v2 solid, MIT — see LICENSE-heroicons.txt). Do not edit. */
export const ICON_PATH_LST: Record<string, string> = ${JSON.stringify(registry, null, 0)}

export const ICON_NAMES: string[] = ${JSON.stringify(Object.keys(registry), null, 0)}
`
writeFileSync(outFile, body)
console.log(`baked ${Object.keys(registry).length} icons → ${outFile.split('genoffice/')[1]}`)
